doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        
        # Custom Types para Value Objects
        types:
            user_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\UserIdType
            role_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\RoleIdType
            course_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\CourseIdType
            lesson_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\LessonIdType
            user_course_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\UserCourseIdType
            course_rating_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\CourseRatingIdType
            coupon_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\CouponIdType
            order_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\OrderIdType
            order_item_id: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\OrderItemIdType
            decimal_value_object: Udemy\Shared\Infrastructure\Persistence\Doctrine\Type\DecimalValueObjectType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/User/User'
                prefix: 'Udemy\User\User\Domain'
                alias: User
                mapping: true
            Role:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/User/Role'
                prefix: 'Udemy\User\Role\Domain'
                alias: Role
                mapping: true
            Course:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Course/Course'
                prefix: 'Udemy\Course\Course\Domain'
                alias: Course
                mapping: true
            Lesson:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Course/Lesson'
                prefix: 'Udemy\Course\Lesson\Domain'
                alias: Lesson
                mapping: true
            UserCourse:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/User/Course'
                prefix: 'Udemy\User\Course\Domain'
                alias: UserCourse
                mapping: true
            CourseRating:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Course/Rating'
                prefix: 'Udemy\Course\Rating\Domain'
                alias: CourseRating
                mapping: true
            Coupon:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Coupon/Coupon'
                prefix: 'Udemy\Coupon\Coupon\Domain'
                alias: Coupon
                mapping: true
            Order:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Order/Order'
                prefix: 'Udemy\Order\Order\Domain'
                alias: Order
                mapping: true
            OrderItem:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Order/Item'
                prefix: 'Udemy\Order\Item\Domain'
                alias: OrderItem
                mapping: true
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
