framework:
    messenger:
        # Transport para mensajes fallidos
        failure_transport: failed

        transports:
            # Transport async usando RabbitMQ
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
            # Transport para mensajes fallidos
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            Udemy\Shared\Domain\Bus\Event\DomainEvent: async
            Udemy\User\User\Domain\Event\UserCreated: async
