# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Udemy\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Http/V1/Request/'

    # Controllers configuration
    Udemy\Http\V1\Controller\:
        resource: '../src/Http/V1/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Command Bus configuration
    Udemy\Shared\Domain\Bus\Command\CommandBus:
        alias: Udemy\Shared\Infrastructure\Bus\Command\SymfonyCommandBus

    # Event Bus configuration
    Udemy\Shared\Domain\Bus\Event\EventBus:
        alias: Udemy\Shared\Infrastructure\Bus\Event\SymfonyEventBus

    # User Repository configuration
    Udemy\User\User\Domain\Repository\UserRepository:
        alias: Udemy\User\User\Infrastructure\Persistence\Doctrine\DoctrineUserRepository

    # Role Repository configuration
    Udemy\User\Role\Domain\Repository\RoleRepository:
        alias: Udemy\User\Role\Infrastructure\Persistence\Doctrine\DoctrineRoleRepository

    # Email Sender configuration
    Udemy\User\User\Application\Service\EmailSender:
        alias: Udemy\User\User\Infrastructure\Service\MailerEmailSender

    # MailerEmailSender configuration
    Udemy\User\User\Infrastructure\Service\MailerEmailSender:
        lazy: true
        arguments:
            $fromEmail: '%env(MAILER_FROM_EMAIL)%'

    # ConfirmationUrlGenerator configuration
    Udemy\User\User\Application\Service\ConfirmationUrlGenerator:
        alias: Udemy\User\User\Infrastructure\Service\JWTConfirmationUserUrlGenerator

    # JWTConfirmationUserUrlGenerator configuration
    Udemy\User\User\Infrastructure\Service\JWTConfirmationUserUrlGenerator:
        arguments:
            $secret: '%env(EMAIL_SECRET)%'
